<?php

/**
  * Copyright (C) 2026 Entidad Pública Empresarial Red.es
  *
  * This file is part of "dge_theme (datos.gob.es)".
  *
  * This program is free software: you can redistribute it and/or modify
  * it under the terms of the GNU General Public License as published by
  * the Free Software Foundation, either version 2 of the License, or
  * (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  * GNU General Public License for more details.
  *
  * You should have received a copy of the GNU General Public License
  * along with this program. If not, see <http://www.gnu.org/licenses/>.
*/


/**
 * @file
 * 
 */

use Drupal\Core\Render\Markup;
use Drupal\Core\Template\Attribute; 
use Drupal\Core\Menu\MenuLinkInterface;
use Drupal\Core\Menu\MenuLinkManagerInterface;
use Drupal\Core\Menu\MenuTreeParameters;
use Drupal\Core\Url;
use Drupal\Core\Render\RendererInterface;
use Drupal\block\BlockRepositoryInterface;
use Drupal\Core\Access\AccessResultInterface;

/**
 * Implements hook_preprocess_image_widget().
 */
function dge_theme_preprocess_image_widget(array &$variables) {
  $data = &$variables['data'];

  if (isset($data['preview']['#access']) && $data['preview']['#access'] === FALSE) {
    unset($data['preview']);
  }
}


function dge_theme_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {

  if ($hook == 'form' & !empty($variables['element']['#id'])) {
    $suggestions[] = 'form__' . str_replace('-', '_', $variables['element']['#id']);
  }

  if ($hook == 'social_media_links' & !empty($variables['theme_hook_original']) ) {
    $suggestions[] = 'social_media_links__' . str_replace('-', '_', $variables['theme_hook_original']);
  }

 if ($variables['theme_hook_original'] == 'form_element_label')
  {
    $id_item = str_replace('-', '_', $variables['element']['#id']);
    $suggestions[] = 'form_element_label__'.$id_item;
  }

  if ($variables['theme_hook_original'] == 'form_element')
  {
    if(isset($variables['element']['#id'])){
      $id_item = str_replace('-', '_', $variables['element']['#id']);
      $suggestions[] = 'form_element__'.$id_item;
    }

  }



}

use Drupal\block\BlockRepositoryInterface;

/**
 * Implements hook_preprocess_HOOK() for menu templates.
 */
function dge_theme_preprocess_menu__main(&$variables) {
  $block_manager = \Drupal::service('plugin.manager.block');

  $lang_plugin_id = 'language_block:language_interface';
  if ($block_manager->hasDefinition($lang_plugin_id)) {
    $instance = $block_manager->createInstance($lang_plugin_id, []);
    $access = $instance->access(\Drupal::currentUser(), TRUE);
    if ($access->isAllowed()) {
      $build = $instance->build();
      $build['#cache']['contexts'][] = 'languages:language_interface';
      $build['#cache']['contexts'][] = 'route';
      $build['#cache']['contexts'][] = 'url';
      $variables['language_switcher'] = $build;
    }
  }

  $user_plugin_id = 'system_menu_block:account';
  if ($block_manager->hasDefinition($user_plugin_id)) {
    $instance = $block_manager->createInstance($user_plugin_id, []);
    $access = $instance->access(\Drupal::currentUser(), TRUE);
    if ($access->isAllowed()) {
      $build = $instance->build();
      // Añadimos contextos de caché adecuados
      $build['#cache']['contexts'][] = 'user.roles';
      $build['#cache']['contexts'][] = 'session';
      $build['#cache']['contexts'][] = 'route';
      $variables['user_profile'] = $build;
    }
  }


}

/**
 * Implements hook_preprocess_HOOK() for paragraphs.
 */
function dge_theme_preprocess_paragraph(&$variables) {
  if ($variables['paragraph']->getType() === 'formulario_peticion_de_datos') {
    $node = \Drupal\node\Entity\Node::create([
      'type' => 'peticion_de_datos',
    ]);
    $variables['form'] = \Drupal::service('entity.form_builder')->getForm($node, 'default');
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for views.
 *
 */
function dge_theme_theme_suggestions_views_view_alter(array &$suggestions, array $variables) {
  if (isset($variables['view']->element['#type'])) {
    $pieces = [
      $variables['view']->element['#type'],
    ];
    $suggestions[] = 'views_' . implode('__', $pieces);
    $pieces = [
      $variables['view']->element['#type'],
      $variables['view']->element['#name'],
    ];
    $suggestions[] = 'views_' . implode('__', $pieces);
    $pieces = [
      $variables['view']->element['#type'],
      $variables['view']->element['#name'],
      $variables['view']->element['#display_id'],
    ];
    $suggestions[] = 'views_' . implode('__', $pieces);
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() for views unformatted rows.
 *
 */
function dge_theme_theme_suggestions_views_view_unformatted_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];
  $suggestions[] = 'views_view_unformatted__' . $view->id();
  $suggestions[] = 'views_view_unformatted__' . $view->id() . '__' . $view->current_display;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter() 
 *
 */
function dge_theme_theme_suggestions_views_view_fields_alter(array &$suggestions, array $variables) {
  $view = $variables['view'];
  $suggestions[] = 'views_view_fields__' . $view->id();
  $suggestions[] = 'views_view_fields__' . $view->id() . '__' . $view->current_display;
}

/**
 * Implements hook_theme_suggestions_HOOK_alter()
 *
 */
function dge_theme_theme_suggestions_sitemap_menu_alter(array &$suggestions, array $variables) {
  if (!empty($variables['menu_name'])) {
    $suggestions[] = 'sitemap_menu__' . str_replace('-', '_', $variables['menu_name']);
  }
}

/**
 * Implements hook_preprocess_HOOK() for links.
 *
 */
function dge_theme_preprocess_links(&$variables) {
  $variables['current_language'] = \Drupal::languageManager()->getCurrentLanguage()->getId();
}

/**
 * Implements hook_preprocess_user().
 *
 */
function dge_theme_preprocess_user(array &$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();
  $user = \Drupal::routeMatch()->getParameter('user');
  if ($user && is_object($user)) {
    $current_user_id = $user->id();
    $variables['is_user_profile'] = ($route_name == 'entity.user.canonical' && $current_user_id == $variables['user']->id());
  }
  else {
    $variables['is_user_profile'] = FALSE;
  }
}


/**
 * Implements hook_preprocess_HOOK()
 *
 *
*/
function dge_theme_preprocess_facets_item_list__links(array &$variables) {
  $term_state_data = [];
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('estados_disponibilidad_de_datos');

  foreach ($terms as $term_info) {
    $term = \Drupal\taxonomy\Entity\Term::load($term_info->tid);
    $color_value = $term->get('field_color')->getValue();
    $color = !empty($color_value[0]['color']) ? $color_value[0]['color'] : NULL;
    $icono_value = $term->get('field_icono')->getValue();
    $icono_url = NULL;
    if (!empty($icono_value[0]['target_id'])) {
      $file = \Drupal\file\Entity\File::load($icono_value[0]['target_id']);
      $icono_url = $file ? $file->createFileUrl() : NULL;
    }

    $term_state_data[$term->label()] = [
      'color' => $color,
      'icono' => $icono_url,
    ];
  }

  $variables['term_state_data'] = $term_state_data;
  $current_request = \Drupal::request();
  $variables['complete_url'] = $current_request->getUri();
}

function dge_theme_preprocess_taxonomy_term__estados_disponibilidad_de_datos(array &$variables) {
  $term = $variables['term'];
  if ($term->hasTranslation(\Drupal::languageManager()->getCurrentLanguage()->getId())){
    $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();
    $term = $term->getTranslation($current_language);
    $variables['name'] = $term->getName();
  }
}

/**
 * Implements hook_preprocess_node().
 */
function dge_theme_preprocess_node__desafio_aporta(&$variables) {
  $terms_data = [];
  $terms = \Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('situaciones_aporta');
  foreach ($terms as $term_info) {
    $term = \Drupal\taxonomy\Entity\Term::load($term_info->tid);
    if ($term->hasTranslation(\Drupal::languageManager()->getCurrentLanguage()->getId())){
      $current_language = \Drupal::languageManager()->getCurrentLanguage()->getId();
      $term = $term->getTranslation($current_language);
    }

    $terms_data[] = [
      'tid' => $term->id(),
      'name' => $term->get('name')->value,
      'field_color' => $term->get('field_color')->value,
      'field_icono' => $term->get('field_icono')->entity,
    ];
  }
  $variables['terms_data'] = $terms_data;
}

/**
 * Implements hook_preprocess_views_exposed_form().
 */
function dge_theme_preprocess_views_exposed_form(&$variables) {
  $form_id = $variables['form']['#id'];
  if ($form_id === 'views-exposed-form') {
    $variables['#attached']['library'][] = 'dge_theme/date-input-filter_js';
  }
}

/**
 * Implementación de hook_form_alter().
 */
function dge_theme_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) : void {

  $form_ids = [
    'node_aplicacion_form',
    'node_peticion_de_datos_form',
    'node_iniciativa_form',
    'node_empresa_reutilizadora_form',
    'user_register_form'
  ];

  if (in_array($form_id, $form_ids, true)) {
    $form['actions']['submit']['#submit'][] = 'dge_theme_redirect_submit';
  }

  if ($form_id==='user_register_form' && isset($form['field_organizacion'])) {
    $options = $form['field_organizacion']['widget']['#options'];
    $placeholder = $options['_none'];
    unset($options['_none']);
    $options = ['' => $placeholder] + $options;
    $form['field_organizacion']['widget']['#options'] = $options;
    $form['field_organizacion']['widget']['#empty_value'] = '';
  }

  if ($form_id==='node_iniciativa_form') {
    if(isset($form['field_initiative_admin_level'])){
      $options = $form['field_initiative_admin_level']['widget']['#options'];
      $placeholder = $options['_none'];
      unset($options['_none']);
      $options = ['' => $placeholder] + $options;
      $form['field_initiative_admin_level']['widget']['#options'] = $options;
      $form['field_initiative_admin_level']['widget']['#empty_value'] = '';
    }
    if(isset($form['field_initiative_category'])){
      $options = $form['field_initiative_category']['widget']['#options'];
      $placeholder = $options['_none'];
      unset($options['_none']);
      $options = ['' => $placeholder] + $options;
      $form['field_initiative_category']['widget']['#options'] = $options;
      $form['field_initiative_category']['widget']['#empty_value'] = '';
    }
  }

  if ($form_id === 'node_empresa_reutilizadora_form') {
    if (isset($form['field_tamano_de_la_empresa'])) {
      $options = $form['field_tamano_de_la_empresa']['widget']['#options'];
      $placeholder = $options['_none'];
      unset($options['_none']);
      $options = ['' => $placeholder] + $options;
      $form['field_tamano_de_la_empresa']['widget']['#options'] = $options;
      $form['field_tamano_de_la_empresa']['widget']['#empty_value'] = '';
    }
  }

  if ($form_id === 'node_peticion_de_datos_edit_form') {
    $form['title']['widget']['#disabled'] = TRUE;
    $form['field_categoria']['widget']['#disabled'] = TRUE;
    unset($form['field_categoria']['widget']['#description']);
    $form['field_descripcion']['widget']['#disabled'] = TRUE;
    $form['field_motivo_de_la_peticion']['widget']['#disabled'] = TRUE;
    $form['field_nombre_y_apellidos']['widget']['#disabled'] = TRUE;
    $form['field_correo_electronico']['widget']['#disabled'] = TRUE;
    $form['field_organizacion']['widget']['#disabled'] = TRUE;
    $form['field_acepto_las_condiciones_del']['widget']['#disabled'] = TRUE;
    unset($form['field_deseo_que_mi_nombre_y_orga']['widget']);
  }

  if ($form_id === 'tfa_entry_form') {
    $config_tfa = \Drupal::config('tfa.settings');
    $default_validation_plugin = $config_tfa->get('default_validation_plugin');
    $plugin = \Drupal::request()->query->get('plugin');
    $is_email_otp = true;
    if ($plugin === 'tfa_totp' || $default_validation_plugin === 'tfa_totp') {
      $is_email_otp = false;
    }
    $config = \Drupal::config('dge_tfa.settings');
    $form['actions']['send']['#prefix'] = '<div class="tfa-button">';
    $form['actions']['send']['#suffix'] = '</div>';
    $form['actions']['login']['#prefix'] = '<div class="tfa-button">';
    $form['actions']['login']['#suffix'] = '</div>';
    $form['code']['#weight'] = 0;
    $form['code']['#prefix'] = '<div class="tfa-text">';
    $form['code']['#suffix'] = '</div>';
    $form['actions']['login']['#weight'] = 10;
    $form['#attributes']['class'][] = 'tfa-entry-form';

    $form['#attached']['library'][] = 'dge_theme/tfa-action_js';

    if ($is_email_otp) {
      $description1 = $config->get('dge-tfa-step1');
      if (!empty($description1['value']) && !empty($description1['format'])) {
        $elements = [
          '#type' => 'processed_text',
          '#text' => t($description1['value']),
          '#format' => $description1['format'],
        ];
        $rendered_description = \Drupal::service('renderer')->renderPlain($elements);
        $description1 = Markup::create($rendered_description);
      } else {
        $description1 = t('<p><b>PASO 1:</b> Por favor pulsa el botón <b>Enviar</b> para recibir un <i><b>código de identificación</b></i> en tu cuenta de correo electrónico.</p>');
      }
      $form['tfa_description_paso1'] = [
        '#type' => 'markup',
        '#markup' => $description1,
        '#weight' => -15,
        '#prefix' => '<div class="dge-tfa-description dge-tfa-step-1">',
        '#suffix' => '</div>',
      ];

      $form['validation_send'] = $form['actions']['send'];
      $form['validation_send']['#weight'] = -10;

      unset($form['actions']['send']);
      $description2 = $config->get('dge-tfa-step2');
      if (!empty($description2['value']) && !empty($description2['format'])) {
        $elements = [
          '#type' => 'processed_text',
          '#text' => t($description2['value']),
          '#format' => $description2['format'],
        ];
        $rendered_description = \Drupal::service('renderer')->renderPlain($elements);
        $description2 = Markup::create($rendered_description);
      } else {
        $description2 = t('<p><b>Step 1:</b> Una vez recibido, introduce el <i><b>código de identificación</b></i> y pulsa el botón <b>Verificar</b>.</p>');
      }
      $form['tfa_description_paso2'] = [
        '#type' => 'markup',
        '#markup' => $description2,
        '#weight' => -5,
        '#prefix' => '<div class="dge-tfa-description dge-tfa-step-2">',
        '#suffix' => '</div>',
      ];
    }
  }
}

/**
 * Implements hook_preprocess_HOOK()
 */
function dge_theme_preprocess_form(&$variables) {
  if ($variables['element']['#form_id'] === 'tfa_entry_form') {
    $config = \Drupal::config('dge_tfa.settings');
    $description = ($config->get('dge-tfa-description')!=null)?$config->get('dge-tfa-description'):null;
    if (!empty($description['value']) && !empty($description['format'])) {
      $elements = [
        '#type' => 'processed_text',
        '#text' => t($description['value']),
        '#format' => $description['format'],
      ];
      $rendered_description = \Drupal::service('renderer')->renderPlain($elements);
      $variables['main_description'] = Markup::create($rendered_description);
    } else {
      $variables['main_description'] = NULL;
    }
  }
}

function dge_theme_redirect_submit(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $current_url = \Drupal::request()->getRequestUri();

  if (isset($form['#form_id'])) {
    $form_id = $form['#form_id'];
    if ($form_id == 'user_pass') {
      $form_state->setRedirectUrl(Url::fromUserInput($current_url));
      $username = $form_state->getValue('name');
      \Drupal::messenger()->addStatus(t('Si @username es una cuenta válida, se le enviará un correo electrónico con instrucciones para restablecer su contraseña.'));
    } else {
      $form_state->setRedirectUrl(Url::fromUserInput($current_url));
    }
  }
}


function dge_flatten_menu(array $items, array &$flat) {
  foreach ($items as $item) {
    $flat[$item->link->getPluginId()] = $item->link;

    if (!empty($item->subtree)) {
      dge_flatten_menu($item->subtree, $flat);
    }
  }
}


/**
 * Implements hook_proprocess_breadcrumb().
 */
function dge_theme_preprocess_breadcrumb(&$variables) {

  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();
  $node_type = $route_match->getParameter('node_type');
  $node = $route_match->getParameter('node');
  $breadcrumb_conocimiento_text=[];

  if ($route_name === 'node.add' && $node_type &&
    ($node_type->id() === 'aplicacion' 
    || $node_type->id() === 'empresa_reutilizadora'
    || $node_type->id() === 'iniciativa')) {


    $custom_titles = [
    'aplicacion'            => t('Share your application'),
    'empresa_reutilizadora' => t('Share your company'),
    'iniciativa'            => t('Share your initiative'),
    ];

    $node_type_id = $node_type->id();

    if (isset($custom_titles[$node_type_id])) {
      $custom_title = $custom_titles[$node_type_id];
    }

    if (!empty($variables['breadcrumb'])) {
      $last_index = array_key_last($variables['breadcrumb']);

      if ($last_index !== null) {
          $variables['breadcrumb'][$last_index]['text'] = $custom_title;
      }
    } else {
      $variables['breadcrumb'][] = [
        'text' => $custom_title,
        'attributes' => new Attribute(['class' => ['active']]),
      ];
    }

    $filtered_breadcrumb[] = [
      'text' => $custom_title,
      'attributes' => new Attribute(['class' => ['active']]),
    ];

    $variables['breadcrumb'] = $filtered_breadcrumb;
    $variables['#cache']['contexts'][] = 'url';

  }


  elseif (str_contains($route_name, 'view') && str_contains($route_name, 'buscador')) {
    // Se asigna como título por defecto 'Search' cuando estamos en el buscador
    $custom_title = t('Search');
    $filtered_breadcrumb[] = [
      'text' => $custom_title,
      'attributes' => new Attribute(['class' => ['active']]),
    ];

    $variables['breadcrumb'] = $filtered_breadcrumb;
  }


  elseif ($route_name === 'tfa.entry') {
    $config = \Drupal::config('dge_tfa.settings');
    $custom_title  = ($config->get('dge-tfa-title')!=null)?$config->get('dge-tfa-title'):'Account verification';

    $variables['breadcrumb'][] = [
      'text' => t($custom_title),
      'attributes' => new Attribute(['class' => ['active']]),
    ];
  } else {

    if (!empty($variables['breadcrumb'])) {

      $request = \Drupal::request();
      $route = $route_match->getRouteObject();
      $title_resolver = \Drupal::service('title_resolver');
      $page_title = $title_resolver->getTitle($request, $route);

      $normalized_page_title = strtolower((string) $page_title);

      $filtered = [];

      $is_knowledge = ['conocimiento', 'knowledge', 'coneixement', 'coñecemento', 'ezagutzaren'];
      if ( count($variables['breadcrumb']) > 1 
        && isset($variables['breadcrumb'][1]['text'])
        && is_string($variables['breadcrumb'][1]['text'])
        && in_array(strtolower(strip_tags($variables['breadcrumb'][1]['text'])), $is_knowledge)
      ) {
        $path_conocimiento = \Drupal::service('path.current')->getPath();

        $path = ltrim($path_conocimiento, '/');

        $parts = explode('/', $path);

        if ($parts[0] !== 'node') {
          if (count($parts) < 3 || $parts[0] !== 'conocimiento' || $parts[1] !== 'tipo') {
            return NULL; // No coincide el patrón esperado.
          }

          $term = $parts[2];

          if ($parts[2] === 'tipo' && isset($parts[3])) {
            $term = $parts[3];
          }

          $term = preg_replace('/-\d+$/', '', $term);

          $term = str_replace('-', ' ', $term);

          if ($term == 'informes y estudios') {
            $term = "informes y guias";
          }

          $breadcrumb_conocimiento_text =[
            'text'       => $term,
            'attributes' => ""
          ] ;
        }
      }
      
      foreach ($variables['breadcrumb'] as $item) {
        if (isset($item['text']) && is_string($item['text'])) {
          $txt = strtolower(strip_tags($item['text'] ?? ''));
        }
        if (isset($item['url']) && $txt === $normalized_page_title) {
          continue;
        }
        $filtered[] = $item;
      }

      // Añadir título actual
      if (!empty($page_title)) {
        $filtered[] = [
          'text'       => $page_title,
          'attributes' => new Attribute(['class' => ['active']])
        ];
      }

      $variables['breadcrumb'] = $filtered;
      $variables['#cache']['contexts'][] = 'url';
    }
  }

  $menu_tree = \Drupal::menuTree();
  $tree = $menu_tree->load('main', new MenuTreeParameters());
  $flat_menu = [];
  dge_flatten_menu($tree, $flat_menu);

  $breadcrumb_labels = [];
  foreach ($variables['breadcrumb'] as $item) {
    $text = $item['text'] ?? '';
    if ($text instanceof \Drupal\Core\StringTranslation\TranslatableMarkup) {
      $text = $text->__toString();
    }
    elseif (is_array($text) && isset($text['#markup'])) {
      $text = $text['#markup'];
    }
    elseif (is_array($text)) {
      $text = '';
    }

    $label = strip_tags((string) $text);
    if (strtolower($label) !== strtolower(t('Home'))) {
      $breadcrumb_labels[] = $label;
    }
  }

  $breadcrumb_for_menu = strtolower(
    count($breadcrumb_labels) > 1 ?
    $breadcrumb_labels[count($breadcrumb_labels) - 2] :
    end($breadcrumb_labels)
  );

  if($breadcrumb_for_menu === 'bloga'){
    $breadcrumb_for_menu= 'blog-a';
  }
  if($breadcrumb_for_menu === 'gertaerak'){
    $breadcrumb_for_menu= 'jardunaldiak';
  }

  // Buscar item del menú
  $matched = null;
  $menu_link_manager = \Drupal::service('plugin.manager.menu.link');

  foreach ($flat_menu as $link) {
    if (strtolower($link->getTitle()) === $breadcrumb_for_menu) {
      $matched = $link;
      break;
    }
  }

  if ($matched) {
    $menu_labels = [];
    $current = $matched;

    while ($current instanceof \Drupal\Core\Menu\MenuLinkInterface) {
      array_unshift(
        $menu_labels,
        $current->getTitle() === 'Jardunaldiak' ? 'Gertaerak' : $current->getTitle()
      );
      
      $parent = $current->getParent();
      if (!$parent) break;

      try {
        $current = $menu_link_manager->createInstance($parent);
      } catch (\Exception $e) { break; }
    }

    $breadcrumb_labels = array_merge([t('Inicio')], $menu_labels);

    if ( count($variables['breadcrumb']) > 2 ) {
      $last_real = end($variables['breadcrumb']);
      if (!empty($last_real['text'])) {
        $breadcrumb_labels[] = strip_tags($last_real['text']);
      }
    } elseif (count($variables['breadcrumb']) &&  
    ( !empty($breadcrumb_conocimiento_text) &&  !empty(($breadcrumb_conocimiento_text['text']))) ) {
      $breadcrumb_labels[] = strip_tags($breadcrumb_conocimiento_text['text']);
    }
  }

  $current = strtolower($breadcrumb_labels[0]);

  $map = [
    strtolower(t('Share your application')) => t('Applications'),
    strtolower(t('Share your company'))     => t('Companies'),
    strtolower(t('Share your initiative'))  => t('Initiatives'),
  ];

  if (isset($map[$current])) {
    array_unshift($breadcrumb_labels, $map[$current]);
    array_unshift($breadcrumb_labels, t('Comunidad'));
    array_unshift($breadcrumb_labels, t('Inicio'));
  }

  if (empty($breadcrumb_labels) || strtolower($breadcrumb_labels[0]) !== 'inicio') {
    array_unshift($breadcrumb_labels, t('Inicio'));
  }
  if ( isset($node) && $node->getType() === 'desafio_aporta') {
    $node_title = $node->getTitle();

    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
    if( isset($breadcrumb_labels[1]) && ($langcode != 'es' || $langcode != 'gl') 
      && ( $breadcrumb_labels[1] === $node_title  )  )
    {
      $parent_title = '';
      $menu_link_manager_challenge = \Drupal::service('plugin.manager.menu.link');
      $menu_link = $menu_link_manager_challenge->createInstance('menu_link_content:3efcd98a-804e-4184-822f-5a8ecd2d8730');
      $parent_plugin_id = $menu_link->getParent();
      if (!empty($parent_plugin_id)) {
        $parent_link = $menu_link_manager->createInstance($parent_plugin_id);
        $parent_title = $parent_link->getTitle();
      }

      $title_challenge = $menu_link->getTitle();
    
      $breadcrumb_challenge = [
        'text' => $title_challenge,
        'url' => $menu_link->getUrlObject()->toString()
      ];
      array_splice($variables['breadcrumb'], 1, 0, [$breadcrumb_challenge]);
      array_splice($breadcrumb_labels, 1, 0, [$parent_title]);
      array_splice($breadcrumb_labels, 2, 0, [$title_challenge]);
    }
  }

  $variables['attributes']['data-breadcrumb'] = implode('|', $breadcrumb_labels);

  
  $variables['#cache']['contexts'][] = 'url';
}

function dge_theme_preprocess_page_title(&$variables) {
  $route_name = \Drupal::routeMatch()->getRouteName();

  if ($route_name === 'node.add') {
    $node_type = \Drupal::routeMatch()->getParameter('node_type');
    if ($node_type) {

      if($node_type->id() === 'aplicacion'){
        $custom_title = t('Share your application');
      }elseif($node_type->id() === 'empresa_reutilizadora'){
        $custom_title = t('Share your company');
      }elseif($node_type->id() === 'iniciativa'){
        $custom_title = t('Share your initiative');
      }

      $variables['title'] = $custom_title;

      if (isset($variables['page']['#title'])) {
        $variables['page']['#title'] = $custom_title;
      }
    }
  } elseif (strpos($route_name, 'view') !== FALSE && strpos($route_name, 'buscador') !== FALSE) {
   _change_title($variables, 'Search');
  } elseif ($route_name === 'tfa.entry') {
    $config = \Drupal::config('dge_tfa.settings');
    $custom_title  = ($config->get('dge-tfa-title')!=null)?$config->get('dge-tfa-title'):'Account verification';

    _change_title($variables, $custom_title);
  }
}

function _change_title(&$variables, $title) {
  $custom_title = t($title);
  $variables['title'] = $custom_title;

  if (isset($variables['page']['#title'])) {
    $variables['page']['#title'] = $custom_title;
  }
}

/**
 *  Implements hook_theme_preprocess_HOOK() for views 
 */
function dge_theme_preprocess_views_view(array &$variables){
  if (isset($variables['view']) && isset($variables['view']->element['#type'])) {
    $view = $variables['view'];
    $request = \Drupal::request();

    $current_display = $view->current_display;
    $search_text = $request->query->get('text');

    if ($current_display === 'buscador' || ($current_display === 'page_1' && !empty($search_text))) {
      $variables['text_search'] = $search_text;

      $machine_name = $view->id();
      $config = \Drupal::config('views.view.' . $machine_name);
      if ($config) {
        $label = $config->get('label');
        if($machine_name == 'conocimiento' )
        {
          $label = (string)t('documentos');
          $translated_text = t('encontrados para "@texto"', ['@texto' => $variables['text_search']]);
        }
        if($machine_name == 'disponibilidad_de_datos'){
          $label = (string)t('solicitudes de datos');
          $translated_text = t('encontradas para "@texto"', ['@texto' => $variables['text_search']]);
        }if ($machine_name == "blog" || $machine_name == "eventos"){
          $translated_text = t('encontrados para "@texto"', ['@texto' => $variables['text_search']]);
        }else{
          $translated_text = t('encontradas para "@texto"', ['@texto' => $variables['text_search']]);
        }
       
        $total_results = $view->pager ? $view->pager->total_items : 0;
        $variables['total_result_search'] = $total_results;
        $variables['custom_header_searh_result'] = sprintf(
          '%d %s %s',
          $total_results,
          mb_strtolower(t($label)),
          $translated_text
        );
        if (isset( $variables['header']['result'])) {
           $variables['header']['result'] = [
            '#markup' => $custom_header,
          ];
        }
        else {
          $variables['header']['result'] = [
            '#markup' => $custom_header,
          ];
        }
      }
    }
  }
}

function dge_theme_preprocess_views_view_fields(&$variables) {
  $view = $variables['view'];

  $views_target = ['noticias', 'eventos','applications','blog','conocimiento','empresas_reutilizadoras', 'entrevistas'];
  if (in_array($view->id(), $views_target, TRUE)) {
    $langcode = \Drupal::languageManager()->getCurrentLanguage()->getId();
    
    if (isset($variables['fields']['field_etiquetas']) && $langcode !== 'es') {
      $node = $variables['row']->_entity;

      if ($node->hasField('field_etiquetas')) {
        $terms = $node->get('field_etiquetas')->referencedEntities();

        $links = [];
        $aliasManager = \Drupal::service('path_alias.manager');
        foreach ($terms as $term) {
          $term_path = '/taxonomy/term/' . $term->id();
          $alias = $aliasManager->getAliasByPath($term_path, $langcode);
          $links[] = '<a href="/' . $langcode . $alias . '" hreflang="es">' . $term->label() . '</a>';
        }
        $output = implode(' ,', $links);
        $variables['fields']['field_etiquetas']->content = Markup::create($output);
      }
    }
  }
}
